version: '3.9'

services:
    yarn:
        image: node:14
        working_dir: /workspace
        volumes:
            - ./:/workspace
            - modules:/workspace/node_modules
            - yarncache:/workspace/.yarn-cache
        environment:
            - YARN_CACHE_FOLDER=/workspace/.yarn-cache
        entrypoint: yarn
  
    ui:
      image: node:14
      working_dir: /workspace
      volumes:
        - ./:/workspace
        - modules:/workspace/node_modules
        - yarncache:/workspace/.yarn-cache
      entrypoint: yarn run start --host 0.0.0.0
      ports: 
        - 4200:4200
      
volumes:
    modules:
    yarncache:
